### PR TITLE
Update ROADMAP with some proposals

### PR DESCRIPTION
**Pull request by cpiemontese**
Based on some discussions with @cottinisimone I update the ROADMAP with a new proposal for future development, namely the ability to let the user customize the retry function used by the lib.

Moreover, I added a proposal to implement an exponential backoff retry strategy.

### CODE REVIEW

**Review by pdincau — DISMISSED** [review]

**Review by matteosister — COMMENTED** [review]
I think that both the exponential retry and error handler configuration are good ideas.
I'm wondering if it makes sense to expose the configuration to the user (expexially for the exponential backoff), or force it from our side. We are trying to set a standard here, more than creating a library to be released open source.
What do you think?

**Comment by cpiemontese** [comment]
> I think that both the exponential retry and error handler configuration are good ideas. I'm wondering if it makes sense to expose the configuration to the user (expexially for the exponential backoff), or force it from our side. We are trying to set a standard here, more than creating a library to be released open source. What do you think?

Yeah you are right about the exponential backoff. We could do

- custom handler (since it would prove difficult to formalize how errors are handled)
- fixed retry strategy

---

> Let's talk about this. I don't know if the handler should be part of the macro or part of the call invokation

You are right, it's not clear cut. I put it there but usually we offer the ability to do both i.e. define a per-bridge option and then eventually override it in a call.
Having it per-call would mean that users could choose to retry an error for a given call and not retry it for another call, which could be useful.
I don't know what would be better, especially given the purpose of trying to set a standard

**Comment by cpiemontese** [comment]
bump

@cottinisimone @matteosister

**Comment by cpiemontese** [comment]
I updated the proposal

- no more choice of which retry strategy to use, just implement the exponential method instead of the linear one
- added a "`call` level" example of a custom retry handler

**Review by cottinisimone — APPROVED** [review]

**Pull request merged**
